### ISSUE TITLE
THREE is not defined

### ISSUE THREAD

**Issue by luiscerqueira** [videojs/videojs-vr#188]
## Description
Briefly describe the issue.
When trying to use the videojs-vr plugin in a react app, the app crashes.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. npm install videojs-vr@1.7.0
2. run a react application with a videojs component
3. init the vr plugin

### Expected
Video and VR functionality should be working

### Actual
React webpack Unhandled Rejection is thrown, saying that THREE is not defined 

### Error output
Uncaught (in promise) ReferenceError: THREE is not defined
    at Object.../node_modules/three/examples/js/controls/VRControls.js (VRControls.js:5)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module.../node_modules/videojs-vr/dist/videojs-vr.es.js (videojs-vr.es.js:1)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)

![image](https://user-images.githubusercontent.com/26207717/66858554-6d97df00-ef81-11e9-8ead-e44776bdc7a8.png)

## Additional Information
The Three.js examples has the assumption that the THREE object is defined globaly. For some reason, this is not the case when the webpack is used.

#### videojs
v.7.5.5

#### browsers
Chrome

#### OSes
Windows

**Comment by brycehowitson** [comment]
Same problem occurs when using VUE. I would assume this is the same for anything using Webpack. 

Is there any movement on a resolution?

**Comment by lizequn** [comment]
Same here with webpack.

**Comment by thomasdeppisch** [comment]
+1 with webpack.

When building videojs-vr, I get:

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
webvr-polyfill (imported by src/plugin.js)
three (imported by src/plugin.js, src/orbit-orientation-controls.js)
three/examples/js/controls/VRControls.js (imported by src/plugin.js)
three/examples/js/effects/VREffect.js (imported by src/plugin.js)
three/examples/js/controls/OrbitControls.js (imported by src/orbit-orientation-controls.js)
three/examples/js/controls/DeviceOrientationControls.js (imported by src/orbit-orientation-controls.js)

**Comment by sh84** [comment]
For webpack work solution:
```
resolve: {
    alias: {
      'videojs-vr': __dirname + '/node_modules/videojs-vr/dist/videojs-vr.min.js'
    }
  }
```
in webpack config

**Comment by nwaughachukwuma** [comment]
This is not working for me in webpack.config.js and vue.config.js. Please, who has set this up in a Vue App? @sh84 @luiscerqueira

**Comment by nwaughachukwuma** [comment]
I ended up doing `import 'videojs-vr/dist/videojs-vr.min.js`. The doc may have to be updated to reflect this.

**Comment by mskelton** [comment]
It would seem the underlying issue here is with the [rollup-replace.js](https://github.com/videojs/videojs-vr/blob/master/scripts/rollup-replace.js) script which transforms the three.js example files to add an `import * as THREE from 'three'` to the top of the file.  My assumption is that the maintainers added this and tested it in this repository not realizing that transforming node_modules in this source repo will have no affect on downstream projects as three.js will be installed from the registry without the patched code from the rollup plugin.

Not only that, but I see this as a major issue when it comes to semver.  Three.js could at any point change their examples in a patch version as they are just that, examples.  This could result in breaking changes in patch or minor releases.  While the current approach is "clever" as a way to reduce boilerplate in this repo, the old solution of copying the examples into this repo is the correct solution.

**Comment by hgshoggins** [comment]
I'm using `browserify` and simply including from `npm` modules:
```
require('video.js');
require('videojs-vr');
```
and experiencing the same problem with THREE not being defined, but I'm puzzled because seeing the different comments, I'm not sure how to solve it really.

I know I'm asking for a specific case, but maybe if someone can point out some hints that could help someone else.

**Comment by promethyttrium** [comment]
So no solution so far. What makes this really funny is how "Rollup" is supposed to "just work" and here, it's barfing all over the place. LOL

**Comment by mskelton** [comment]
@hgshoggins The solution my company had to resort to was locking down videojs-vr to version 1.4.1.  Hopefully that works for you!

**Comment by promethyttrium** [comment]
This seems like a pretty serious issue with no workaround. Is this being prioritized to be fixed?

**Comment by Brandonza** [comment]
Hi

Has anyone solved this yet?

**Comment by promethyttrium** [comment]
@Brandonza, looks like nobody here really gives a crap...

**Comment by shivarajnaidu** [comment]
is there any solid solution ?

**Comment by Brandonza** [comment]
Not as far as I know

**Comment by azalys** [comment]
> @hgshoggins The solution my company had to resort to was locking down videojs-vr to version 1.4.1. Hopefully that works for you!

Do you find a solution ? 
I downgrade the version to 1.4.1 but I have other compatibility error with videojs.

I've seen something with rollup-replace.js which could fix the problem (maybe) but I don't understand how implemented this in a vue.js app.

Thanks for your help

**Comment by bunday** [comment]
I saw a couple of answers, here is what worked for me on `vue.js`

- import videojs from "video.js";
- Instead of importing `videojs-vr` next, import `videojs-vr/dist/videojs-vr.min.js`

That should do the trick

**Comment by h0jeZvgoxFepBQ2C** [comment]
Doesn't work for me, when I dont call require("videojs-vr") it can't find the vr(..) method.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Did you import THREE seperately?
